// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAr2MpqkJVmGKyHeqVcQKfZDLFbFha1Q',
    appId: '1:755789294127:web:aafe8a9db0c05bc13634da',
    messagingSenderId: '755789294127',
    projectId: 'things-stuffs-a62cb',
    authDomain: 'things-stuffs-a62cb.firebaseapp.com',
    storageBucket: 'things-stuffs-a62cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_weTMZO12hI2JKDkEfFcMqWOYg6JU7Zk',
    appId: '1:755789294127:android:64ffc930649dcc7c3634da',
    messagingSenderId: '755789294127',
    projectId: 'things-stuffs-a62cb',
    storageBucket: 'things-stuffs-a62cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8iNkyMnF1WRCr3ArRJAxXSYd-AUQGc8',
    appId: '1:755789294127:ios:44f2e35465f6e01d3634da',
    messagingSenderId: '755789294127',
    projectId: 'things-stuffs-a62cb',
    storageBucket: 'things-stuffs-a62cb.appspot.com',
    iosBundleId: 'com.example.thingStuffs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB8iNkyMnF1WRCr3ArRJAxXSYd-AUQGc8',
    appId: '1:755789294127:ios:b865599eaa837b493634da',
    messagingSenderId: '755789294127',
    projectId: 'things-stuffs-a62cb',
    storageBucket: 'things-stuffs-a62cb.appspot.com',
    iosBundleId: 'com.example.thingStuffs.RunnerTests',
  );
}
